# For Production comment out the npm run dev command below and uncomment the npm start command, as well as the NODE_ENV enviroment


services: 
  app:
    container_name: face-detector
    build: ./
    volumes: 
      - .:/usr/src/face-detector

    # For development
    command: npm run dev

    # For Production 
    # command: npm start
    working_dir: /usr/src/face-detector
    ports:
      - "3000:3000"
      - "5000:5000"
    env_file: 
      - .env
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/face-detector
      REDIS_URI: redis://redis:6379
      # Remove NODE_ENV for development
      # NODE_ENV: production


  
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/face-detector
      POSTGRES_DB: face-detector
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"